test/transcriptIT
Projet-P3/hei-admin-api pull request #2
Opened 2023-08-01 09:02 UTC by haritianaadriano

Test template for transcript. I already have bug to fix but it's just a test integration.

2023-08-02 05:35 UTC, NyH1409 requested changes

2023-08-02 05:35 UTC, NyH1409 commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +    void student_read_ok() throws ApiException {
Student read what? Be expliciter

2023-08-02 05:35 UTC, NyH1409 commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +    void teacher_read_ok() throws ApiException {
Teacher read what?

2023-08-02 05:35 UTC, NyH1409 commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +
Use Httpclient for testing because our API takes a byte[] as requestbody but not a Java File.

2023-08-02 06:21 UTC, haritianaadriano commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +    void student_read_ok() throws ApiException {
I fixed the method name for more readability

2023-08-02 06:21 UTC, haritianaadriano commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +    void teacher_read_ok() throws ApiException {
Same here

2023-08-02 06:21 UTC, haritianaadriano commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +
ok we will see that

2023-08-02 10:14 UTC, haritianaadriano commented on src/test/java/school/hei/haapi/integration/TranscriptIT.java
> +
can you check ? i finished my test with httpClient to test the post transcript with pdf

2023-08-06 05:55 UTC, NyH1409 approved these changes

2023-08-06 05:57 UTC, merged