Test/student transcript version claim
Projet-P3/hei-admin-api pull request #6
Opened 2023-08-03 16:56 UTC by miharyjoe

2023-08-04 07:21 UTC, NyH1409 requested changes

2023-08-04 07:21 UTC, NyH1409 commented on src/main/resources/db/testdata/V99_9__Test_create_student_transcript_claim.sql
> +(transcript_id, version_id, status,creation_datetime,closed_datetime,reason)
Add another version for one of the transcript. F.e.: transcript1_id -> version4_id

2023-08-04 07:24 UTC, NyH1409 requested changes

2023-08-04 07:24 UTC, NyH1409 commented on src/test/java/school/hei/haapi/integration/StudentTranscriptVersionClaimIT.java
> +    void student_read_student_transcript_version_claim() throws ApiException {
It's confusing. Just write `student_read_transcript_version_claims`

2023-08-04 07:27 UTC, NyH1409 requested changes

2023-08-04 07:27 UTC, NyH1409 commented on src/main/resources/db/migration/V0_14__Create_transcript_table.sql
> +create type "semester" as enum ('M1','M2','M3','M4','M5','M6');
why `M1 ....,M6` but not `S1...S6` ?

2023-08-04 07:37 UTC, NyH1409 requested changes

2023-08-04 07:37 UTC, NyH1409 commented on src/main/java/school/hei/haapi/endpoint/rest/security/SecurityConf.java
> +        .antMatchers(GET,TRANSCRIPT_VERSION_CLAIM).hasAnyRole(STUDENT.getRole())
It should be a SelfMatcher because only the owner of the transcript can view it but not all of students
Don't forget to add test for that

2023-08-06 15:23 UTC, miharyjoe commented on src/test/java/school/hei/haapi/integration/StudentTranscriptVersionClaimIT.java
> +    void student_read_student_transcript_version_claim() throws ApiException {
done

2023-08-06 15:24 UTC, miharyjoe commented on src/main/java/school/hei/haapi/endpoint/rest/security/SecurityConf.java
> +        .antMatchers(GET,TRANSCRIPT_VERSION_CLAIM).hasAnyRole(STUDENT.getRole())
it's done

2023-08-09 09:34 UTC, merged